services:
  app:
    build: . # образ из Dockerfile лежит в текущей папке
    container_name: shareit-app
    ports:
      - "8080:8080" # Мой порт слева, внутри контейнера справа
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILE} # используем профиль для docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${POSTGRES_DB} # под-е к бд внутри контейнера
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=${TZ}  # чтобы установить в контейнере, для прохождения текстов
    depends_on:
      db:
        condition: service_healthy
    networks:
      - shareit-network

  db:
    image: postgres:16.1-alpine
    container_name: shareit-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # лимиты памяти и процессора
    mem_limit: 512m
    cpus: "0.5"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      timeout: 5s
      interval: 5s
      retries: 5
    networks:
      - shareit-network


networks:
  shareit-network:
    driver: bridge

volumes:
  postgres_data: