services:
  app:
    build: . # образ из Dockerfile лежит в текущей папке
    container_name: shareit-app
    ports:
      - "8080:8080" # Мой порт слева, внутри контейнера справа
    environment:
      - SPRING_PROFILES_ACTIVE=docker # используем профиль для docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit # под-е к бд внутри контейнера
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - TZ=Europe/Moscow
    depends_on:
      db:
        condition: service_healthy
    networks:
      - shareit-network

  db:
    image: postgres:16.1-alpine
    container_name: shareit-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d shareit"]
      timeout: 5s
      interval: 5s
      retries: 5
    networks:
      - shareit-network


networks:
  shareit-network:
    driver: bridge

volumes:
  postgres_data: