spring:
  datasource:
    url: jdbc:postgresql://db:5432/shareit
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate     # не создаём таблицы (используем Flyway/схему)
    properties:
      hibernate:
        format_sql: true  # красивое форматирование SQL
        show_sql: false    # показывать SQL в консоли
        use_sql_comments: true   # комментарии в SQL
        jdbc:
          batch_size: 20  # батчинг для производительности
          time_zone: UTC
  sql:
    init:
      mode: always

logging:
  level:
    example: info

server:
  port: 8080