### настройки spring data jpa и sql initialisation
spring:
  jpa:
    hibernate:
      ddl-auto: none     # не создаём таблицы (используем Flyway/схему)
    properties:
     hibernate:
       format_sql: true  # красивое форматирование SQL
       show_sql: true    # показывать SQL в консоли
       use_sql_comments: false   # комментарии в SQL
       jdbc:
         batch_size: 20  # батчинг для производительности

  sql:
    init:
      mode: always  # всегда выполнять schema.sql


 # Настройки DataSource to Postgres DB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/${POSTGRES_DB}"
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

server:
  port: 8080

# Для продакшена логирование
logging:
  level:
    org:
      springframework:
        jpa: warn
        web: warn
    org.hibernate:
      SQL: warn
