spring:
  datasource:
    url: jdbc:postgresql://db:5432/shareit
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  sql:
    init:
      mode: always

logging:
  level:
    example: info

server:
  port: 8080