# файл профиля добавлен в .gitignore, только для разработки локально,
# когда запускаю один сервис db из docker-compose.
# Для этого пишем docker compose --env-file .env up -d db
# Для запуска приложения через консоль используем maven SPRING_PROFILES_ACTIVE=local mvn spring-boot:run
# Можно запускать через профиль через настройки pom.xml
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shareit
    username: user
    password: root

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        jdbc:
          batch_size: 20
          time_zone: UTC

  sql:
    init:
      mode: always

  main:
    banner-mode: off

logging:
  level:
    example: info
    org.hibernate.sql: info


server:
  port: 8081